#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(5, "helloworld")
def test_hello():
    r.run_qemu(shell_script([
        'helloworld', 'echo OK'
    ]))
    r.match('^hello, world$', '^OK$')

run_tests()
