#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(5, "hello")
def test_hello():
    r.run_qemu(shell_script([
        'hello', 'echo OK'
    ]))
    r.match('^hello$', '^OK$')

@test(5, "world")
def test_world():
    r.run_qemu(shell_script([
        'world', 'echo OK'
    ]))
    r.match('^world$', '^OK$')

@test(5, "answers-setup.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-setup.txt")

@test(1, "time")
def test_time():
    check_time()

run_tests()
